SHOW USER;

CREATE TABLE MEMBER_TBL (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PW VARCHAR2(30) NOT NULL,
    MEMBER_NAME VARCHAR2(30) NOT NULL,
    MEMBER_AGE NUMBER,
    MEMBER_GENDER VARCHAR2(6), 
    MEMBER_EMAIL VARCHAR2(50),
    MEMBER_PHONE VARCHAR2(11),
    MEMBER_ADDRESS VARCHAR2(150),
    MEMBER_HOBBY VARCHAR2(100),
    MEMBER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    MEMBER_YN VARCHAR2(1) DEFAULT 'Y'
);

SELECT * FROM MEMBER_TBL;
UPDATE MEMBER_TBL SET MEMBER_NAME = '이용자',  MEMBER_EMAIL='user02@kh.com' WHERE MEMBER_ID='user02';

INSERT INTO MEMBER_TBL VALUES('user02', 'pass02', '일용자', '11', 'M', 'user01@naver.com', '01011111111', '서울시 중구', '낮잠', DEFAULT, DEFAULT, DEFAULT);

SELECT * FROM MEMBER_TBL WHERE MEMBER_ID='khuser01' AND MEMBER_PW='pass01';