--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-11-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "SPRING"."MEMBER_TBL" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(30 BYTE), 
	"MEMBER_AGE" NUMBER, 
	"MEMBER_GENDER" VARCHAR2(6 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(50 BYTE), 
	"MEMBER_PHONE" VARCHAR2(11 BYTE), 
	"MEMBER_ADDRESS" VARCHAR2(150 BYTE), 
	"MEMBER_HOBBY" VARCHAR2(100 BYTE), 
	"MEMBER_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"MEMBER_YN" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SPRING.MEMBER_TBL
SET DEFINE OFF;
Insert into SPRING.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_AGE,MEMBER_GENDER,MEMBER_EMAIL,MEMBER_PHONE,MEMBER_ADDRESS,MEMBER_HOBBY,MEMBER_DATE,UPDATE_DATE,MEMBER_YN) values ('user01','pass01','일용자',11,'M','user01@naver.com','01011111111','서울시 중구 ','코딩',to_timestamp('23/08/11 15:58:34.012000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/11 15:58:34.012000000','RR/MM/DD HH24:MI:SSXFF'),'Y');
Insert into SPRING.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_AGE,MEMBER_GENDER,MEMBER_EMAIL,MEMBER_PHONE,MEMBER_ADDRESS,MEMBER_HOBBY,MEMBER_DATE,UPDATE_DATE,MEMBER_YN) values ('user02','pass02','이용자',11,'M','user02@kh.com','01011111111','서울시 중구','낮잠',to_timestamp('23/08/11 17:15:55.296000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/11 17:15:55.296000000','RR/MM/DD HH24:MI:SSXFF'),'Y');
--------------------------------------------------------
--  DDL for Index SYS_C007254
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."SYS_C007254" ON "SPRING"."MEMBER_TBL" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "SPRING"."MEMBER_TBL" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPRING"."MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
